name: CI Pipeline

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:19.03.12
        options: --privileged
        ports:
          - 2375:2375
    env:
      DOCKER_HOST: tcp://localhost:2375
      DOCKER_DRIVER: overlay2
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Docker info
        run: docker info

      - name: Build
        run: docker compose up -d

      - name: Upload docker-compose.yml
        uses: actions/upload-artifact@v3
        with:
          name: docker-compose
          path: docker-compose.yml

  test:
    runs-on: ubuntu-latest
    needs: build
    services:
      docker:
        image: docker:19.03.12
        options: --privileged
        ports:
          - 2375:2375
    env:
      DOCKER_HOST: tcp://localhost:2375
      DOCKER_DRIVER: overlay2
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download docker-compose.yml
        uses: actions/download-artifact@v3
        with:
          name: docker-compose
          path: .

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip
          python3 -m venv /venv
          source /venv/bin/activate
          pip install pytest selenium

      - name: Start services
        run: docker compose up -d

      - name: Wait for services to be ready
        run: sleep 15

      - name: Run tests
        run: |
          source /venv/bin/activate
          python test_devopstest.py

      - name: Upload docker-compose.yml
        uses: actions/upload-artifact@v3
        with:
          name: docker-compose
          path: docker-compose.yml
